/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tkestack.io/tapp/pkg/apis/tappcontroller/v1/generated.proto

package v1

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"

	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	v11 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *TApp) Reset()      { *m = TApp{} }
func (*TApp) ProtoMessage() {}
func (*TApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea187507033e3e5, []int{0}
}
func (m *TApp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TApp.Merge(m, src)
}
func (m *TApp) XXX_Size() int {
	return m.Size()
}
func (m *TApp) XXX_DiscardUnknown() {
	xxx_messageInfo_TApp.DiscardUnknown(m)
}

var xxx_messageInfo_TApp proto.InternalMessageInfo

func (m *TAppList) Reset()      { *m = TAppList{} }
func (*TAppList) ProtoMessage() {}
func (*TAppList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea187507033e3e5, []int{1}
}
func (m *TAppList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TAppList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TAppList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TAppList.Merge(m, src)
}
func (m *TAppList) XXX_Size() int {
	return m.Size()
}
func (m *TAppList) XXX_DiscardUnknown() {
	xxx_messageInfo_TAppList.DiscardUnknown(m)
}

var xxx_messageInfo_TAppList proto.InternalMessageInfo

func (m *TAppSpec) Reset()      { *m = TAppSpec{} }
func (*TAppSpec) ProtoMessage() {}
func (*TAppSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea187507033e3e5, []int{2}
}
func (m *TAppSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TAppSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TAppSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TAppSpec.Merge(m, src)
}
func (m *TAppSpec) XXX_Size() int {
	return m.Size()
}
func (m *TAppSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TAppSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TAppSpec proto.InternalMessageInfo

func (m *TAppStatus) Reset()      { *m = TAppStatus{} }
func (*TAppStatus) ProtoMessage() {}
func (*TAppStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea187507033e3e5, []int{3}
}
func (m *TAppStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TAppStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TAppStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TAppStatus.Merge(m, src)
}
func (m *TAppStatus) XXX_Size() int {
	return m.Size()
}
func (m *TAppStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TAppStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TAppStatus proto.InternalMessageInfo

func (m *TAppUpdateStrategy) Reset()      { *m = TAppUpdateStrategy{} }
func (*TAppUpdateStrategy) ProtoMessage() {}
func (*TAppUpdateStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea187507033e3e5, []int{4}
}
func (m *TAppUpdateStrategy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TAppUpdateStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TAppUpdateStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TAppUpdateStrategy.Merge(m, src)
}
func (m *TAppUpdateStrategy) XXX_Size() int {
	return m.Size()
}
func (m *TAppUpdateStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_TAppUpdateStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_TAppUpdateStrategy proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TApp)(nil), "tkestack.io.tapp.pkg.apis.tappcontroller.v1.TApp")
	proto.RegisterType((*TAppList)(nil), "tkestack.io.tapp.pkg.apis.tappcontroller.v1.TAppList")
	proto.RegisterType((*TAppSpec)(nil), "tkestack.io.tapp.pkg.apis.tappcontroller.v1.TAppSpec")
	proto.RegisterMapType((map[string]InstanceStatus)(nil), "tkestack.io.tapp.pkg.apis.tappcontroller.v1.TAppSpec.StatusesEntry")
	proto.RegisterMapType((map[string]v11.PodTemplateSpec)(nil), "tkestack.io.tapp.pkg.apis.tappcontroller.v1.TAppSpec.TemplatePoolEntry")
	proto.RegisterMapType((map[string]string)(nil), "tkestack.io.tapp.pkg.apis.tappcontroller.v1.TAppSpec.TemplatesEntry")
	proto.RegisterType((*TAppStatus)(nil), "tkestack.io.tapp.pkg.apis.tappcontroller.v1.TAppStatus")
	proto.RegisterMapType((map[string]InstanceStatus)(nil), "tkestack.io.tapp.pkg.apis.tappcontroller.v1.TAppStatus.StatusesEntry")
	proto.RegisterType((*TAppUpdateStrategy)(nil), "tkestack.io.tapp.pkg.apis.tappcontroller.v1.TAppUpdateStrategy")
}

func init() {
	proto.RegisterFile("tkestack.io/tapp/pkg/apis/tappcontroller/v1/generated.proto", fileDescriptor_0ea187507033e3e5)
}

var fileDescriptor_0ea187507033e3e5 = []byte{
	// 1019 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0x3a, 0x76, 0xb0, 0x27, 0x89, 0xd5, 0x8e, 0x02, 0x5a, 0x59, 0x68, 0x13, 0x99, 0x4b,
	0x10, 0x30, 0x8b, 0x5b, 0xfe, 0x04, 0x52, 0x81, 0xba, 0x6d, 0xa9, 0x82, 0x08, 0x29, 0xe3, 0x24,
	0x48, 0xa8, 0x08, 0xc6, 0xeb, 0xa9, 0xb3, 0x78, 0xff, 0x69, 0x67, 0xd6, 0xc2, 0xe2, 0x00, 0x08,
	0x71, 0xe1, 0x84, 0xf8, 0x08, 0xfd, 0x04, 0x7c, 0x04, 0x8e, 0x39, 0xf6, 0xd8, 0x53, 0x21, 0xe6,
	0x5b, 0x70, 0x42, 0x33, 0x3b, 0xfb, 0x2f, 0xb6, 0xdb, 0x38, 0xb9, 0xed, 0xbc, 0x79, 0xbf, 0xdf,
	0xef, 0xcd, 0x7b, 0x6f, 0xde, 0x2c, 0xd8, 0xe5, 0x43, 0xca, 0x38, 0xb1, 0x87, 0xc8, 0x09, 0x4c,
	0x4e, 0xc2, 0xd0, 0x0c, 0x87, 0x03, 0x93, 0x84, 0x0e, 0x93, 0x2b, 0x3b, 0xf0, 0x79, 0x14, 0xb8,
	0x2e, 0x8d, 0xcc, 0x51, 0xc7, 0x1c, 0x50, 0x9f, 0x46, 0x84, 0xd3, 0x3e, 0x0a, 0xa3, 0x80, 0x07,
	0xf0, 0x8d, 0x02, 0x18, 0x09, 0x77, 0x14, 0x0e, 0x07, 0x48, 0x80, 0x51, 0x19, 0x8c, 0x46, 0x9d,
	0xd6, 0x5b, 0x03, 0x87, 0x9f, 0xc4, 0x3d, 0x64, 0x07, 0x9e, 0x39, 0x08, 0x06, 0x81, 0x29, 0x39,
	0x7a, 0xf1, 0x23, 0xb9, 0x92, 0x0b, 0xf9, 0x95, 0x70, 0xb7, 0xda, 0xc3, 0x1d, 0x26, 0x62, 0x22,
	0xa1, 0x63, 0xda, 0x41, 0x44, 0x67, 0xe8, 0xb7, 0xde, 0xc9, 0x7d, 0x3c, 0x62, 0x9f, 0x38, 0x3e,
	0x8d, 0xc6, 0x79, 0xfc, 0x1e, 0xe5, 0x64, 0x16, 0xca, 0x9c, 0x87, 0x8a, 0x62, 0x9f, 0x3b, 0x1e,
	0x9d, 0x02, 0xbc, 0xf7, 0x22, 0x00, 0xb3, 0x4f, 0xa8, 0x47, 0xa6, 0x70, 0x37, 0xe7, 0xe1, 0x62,
	0xee, 0xb8, 0xa6, 0xe3, 0x73, 0xc6, 0xa3, 0xf3, 0xa0, 0xf6, 0xe3, 0x0a, 0xa8, 0x1e, 0xde, 0x0e,
	0x43, 0xf8, 0x2d, 0xa8, 0x8b, 0x13, 0xf4, 0x09, 0x27, 0xba, 0xb6, 0xa5, 0x6d, 0xaf, 0xde, 0x78,
	0x1b, 0x25, 0x84, 0xa8, 0x48, 0x98, 0xa7, 0x5c, 0x78, 0xa3, 0x51, 0x07, 0x1d, 0xf4, 0xbe, 0xa3,
	0x36, 0xdf, 0xa7, 0x9c, 0x58, 0xf0, 0xf4, 0xd9, 0xe6, 0xd2, 0xe4, 0xd9, 0x26, 0xc8, 0x6d, 0x38,
	0x63, 0x85, 0x5f, 0x82, 0x2a, 0x0b, 0xa9, 0xad, 0x57, 0x24, 0xfb, 0xbb, 0x68, 0x81, 0x6a, 0x22,
	0x11, 0x62, 0x37, 0xa4, 0xb6, 0xb5, 0xa6, 0x24, 0xaa, 0x62, 0x85, 0x25, 0x21, 0xfc, 0x06, 0xac,
	0x30, 0x4e, 0x78, 0xcc, 0xf4, 0x65, 0x49, 0xfd, 0xfe, 0xe2, 0xd4, 0x12, 0x6e, 0x35, 0x15, 0xf9,
	0x4a, 0xb2, 0xc6, 0x8a, 0xb6, 0xfd, 0x97, 0x06, 0xea, 0xc2, 0xed, 0x33, 0x87, 0x71, 0xf8, 0x70,
	0x2a, 0x51, 0xe8, 0x62, 0x89, 0x12, 0x68, 0x99, 0xa6, 0x6b, 0x4a, 0xa6, 0x9e, 0x5a, 0x0a, 0x49,
	0x3a, 0x06, 0x35, 0x87, 0x53, 0x8f, 0xe9, 0x95, 0xad, 0xe5, 0xed, 0xd5, 0x1b, 0x9d, 0x85, 0x8f,
	0x62, 0xad, 0x2b, 0xf6, 0xda, 0x9e, 0xe0, 0xc1, 0x09, 0x5d, 0xfb, 0x31, 0x48, 0x8e, 0x20, 0xd2,
	0x06, 0xdf, 0x04, 0xf5, 0x88, 0x86, 0xae, 0x63, 0x13, 0x26, 0x8f, 0x50, 0xcb, 0x43, 0xc2, 0xca,
	0x8e, 0x33, 0x0f, 0xf8, 0x35, 0xa8, 0x33, 0xea, 0x52, 0x9b, 0x07, 0x91, 0xaa, 0xdd, 0xcd, 0x0b,
	0x1e, 0x98, 0xf4, 0xa8, 0xdb, 0x55, 0x50, 0x6b, 0x4d, 0xd0, 0xa7, 0x2b, 0x9c, 0x51, 0xc2, 0x2f,
	0x40, 0x9d, 0x53, 0x2f, 0x74, 0x09, 0xa7, 0xaa, 0x7e, 0xaf, 0x15, 0xe8, 0x91, 0xb8, 0x8c, 0x82,
	0xec, 0x41, 0xd0, 0x3f, 0x54, 0x6e, 0xb2, 0x11, 0xb2, 0x88, 0x53, 0x2b, 0xce, 0x68, 0xe0, 0xcf,
	0x1a, 0x58, 0x4b, 0x17, 0x0f, 0x82, 0xc0, 0xd5, 0xab, 0x32, 0x99, 0xf7, 0x2f, 0xd5, 0x72, 0xe8,
	0xb0, 0xc0, 0x74, 0xcf, 0xe7, 0xd1, 0xd8, 0xda, 0x50, 0xda, 0x6b, 0xc5, 0x2d, 0x5c, 0x92, 0x84,
	0xbf, 0x68, 0xa0, 0x9e, 0xb4, 0x0f, 0x65, 0x7a, 0x4d, 0xea, 0xdf, 0xb9, 0x9c, 0x7e, 0x57, 0xb1,
	0x24, 0xda, 0xed, 0xf4, 0xdc, 0xa9, 0xf9, 0xb7, 0xbf, 0x37, 0x9b, 0x7b, 0x3e, 0xe3, 0xc4, 0xb7,
	0xa9, 0xea, 0xdb, 0x4c, 0x18, 0xc6, 0xa0, 0x91, 0x46, 0xc5, 0xf4, 0x15, 0x19, 0xc5, 0xdd, 0xab,
	0x65, 0x41, 0x85, 0x71, 0x5d, 0x85, 0xd1, 0xc8, 0xec, 0x38, 0x57, 0x82, 0x3f, 0x82, 0x66, 0x1c,
	0xf6, 0x45, 0xa9, 0xb8, 0x18, 0x36, 0x83, 0xb1, 0xfe, 0x92, 0xac, 0xec, 0xc7, 0x0b, 0x6b, 0x1f,
	0x95, 0x68, 0xac, 0x57, 0x94, 0x6c, 0xb3, 0x6c, 0xc7, 0xe7, 0xe4, 0xe0, 0x47, 0xa0, 0xf9, 0x28,
	0x88, 0x6c, 0x7a, 0x97, 0xba, 0x54, 0x14, 0xa4, 0xaf, 0xd7, 0xb7, 0xb4, 0xed, 0x7a, 0x8e, 0xff,
	0xa4, 0xb4, 0x8b, 0xcf, 0x79, 0xc3, 0x87, 0x40, 0x27, 0x31, 0x0f, 0x12, 0xc3, 0x91, 0x1f, 0x33,
	0x9a, 0x75, 0x9f, 0xde, 0x90, 0x4c, 0x5b, 0x8a, 0x49, 0xbf, 0x3d, 0xc7, 0x0f, 0xcf, 0x65, 0x80,
	0x3b, 0x60, 0xcd, 0xa7, 0x23, 0x1a, 0xed, 0x3b, 0x03, 0x11, 0xaf, 0x0e, 0x24, 0x63, 0xd6, 0x55,
	0x9f, 0x17, 0xf6, 0x70, 0xc9, 0x13, 0xfe, 0x00, 0x36, 0x46, 0x81, 0x1b, 0x7b, 0xf4, 0x8e, 0x4b,
	0x1c, 0x2f, 0xcb, 0xbd, 0xbe, 0x2a, 0x4b, 0xfb, 0xfa, 0xcc, 0x8b, 0x43, 0x23, 0xe6, 0x30, 0x4e,
	0x7d, 0x7e, 0x9c, 0x23, 0xad, 0x57, 0x95, 0xd8, 0xc6, 0xf1, 0x0c, 0x3a, 0x3c, 0x53, 0xa4, 0xd5,
	0x07, 0xd7, 0xa7, 0xee, 0x02, 0xbc, 0x06, 0x96, 0x87, 0x74, 0x2c, 0xc7, 0x48, 0x03, 0x8b, 0x4f,
	0xf8, 0x01, 0xa8, 0x8d, 0x88, 0x1b, 0x53, 0x35, 0x2c, 0x2e, 0x72, 0x9b, 0x71, 0x82, 0xf8, 0xb0,
	0xb2, 0xa3, 0xb5, 0x76, 0xc1, 0x7a, 0xa9, 0xe3, 0x67, 0x28, 0x6c, 0x14, 0x15, 0x1a, 0x45, 0xf0,
	0x2d, 0xd0, 0x2c, 0x37, 0xea, 0x22, 0xe8, 0xf6, 0x1f, 0x55, 0x00, 0xf2, 0xe7, 0x00, 0x7e, 0x0a,
	0x60, 0xd0, 0x63, 0x34, 0x1a, 0xd1, 0xfe, 0xfd, 0xe4, 0xd9, 0x74, 0x02, 0x5f, 0x32, 0x2d, 0x5b,
	0x2d, 0x95, 0x3f, 0x78, 0x30, 0xe5, 0x81, 0x67, 0xa0, 0x4a, 0x23, 0xb7, 0xf2, 0xc2, 0x91, 0xbb,
	0x0b, 0xd6, 0x23, 0x4a, 0xfa, 0xe3, 0x74, 0x4b, 0x0e, 0xc6, 0x9a, 0xf5, 0xb2, 0x82, 0xac, 0xe3,
	0xe2, 0x26, 0x2e, 0xfb, 0x8a, 0xb0, 0x99, 0x4d, 0x5c, 0x5a, 0x1a, 0xbf, 0x7a, 0x55, 0x1c, 0x36,
	0x0f, 0xbb, 0x3b, 0xe5, 0x81, 0x67, 0xa0, 0xe0, 0x2d, 0xd0, 0x20, 0x69, 0x3e, 0xf4, 0x9a, 0xa4,
	0x30, 0xd2, 0x9b, 0x9f, 0x25, 0xea, 0xbf, 0xe2, 0x02, 0xe7, 0x00, 0xf8, 0x6b, 0x71, 0x06, 0x26,
	0xd3, 0xe7, 0xde, 0x25, 0xdf, 0xe6, 0xab, 0x4c, 0xc1, 0x2b, 0xb5, 0x54, 0xfb, 0x4f, 0x0d, 0xc0,
	0xe9, 0x49, 0x24, 0x0a, 0x9a, 0x3d, 0x5b, 0x92, 0xe7, 0xb9, 0x2f, 0x92, 0x0b, 0x9a, 0x1e, 0xf9,
	0xfe, 0xc8, 0x27, 0x23, 0xe2, 0xb8, 0xa4, 0xe7, 0xa6, 0x97, 0x63, 0xfe, 0x3f, 0x96, 0xf8, 0x69,
	0x43, 0xc9, 0x4f, 0x1b, 0xda, 0xf3, 0xf9, 0x41, 0xd4, 0xe5, 0x91, 0xe3, 0x0f, 0x2c, 0x28, 0xa6,
	0xd7, 0x7e, 0x89, 0x0b, 0x9f, 0xe3, 0xb6, 0xb6, 0x4f, 0xcf, 0x8c, 0xa5, 0x27, 0x67, 0xc6, 0xd2,
	0xd3, 0x33, 0x63, 0xe9, 0xa7, 0x89, 0xa1, 0x9d, 0x4e, 0x0c, 0xed, 0xc9, 0xc4, 0xd0, 0x9e, 0x4e,
	0x0c, 0xed, 0x9f, 0x89, 0xa1, 0xfd, 0xfe, 0xaf, 0xb1, 0xf4, 0x55, 0x65, 0xd4, 0xf9, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0x0a, 0x8f, 0xac, 0xf8, 0x90, 0x0b, 0x00, 0x00,
}

func (m *TApp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TApp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TApp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TAppList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TAppList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TAppList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TAppSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TAppSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TAppSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VolumeClaimTemplates) > 0 {
		for iNdEx := len(m.VolumeClaimTemplates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VolumeClaimTemplates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	i--
	if m.NeverMigrate {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x50
	i--
	if m.AutoDeleteUnusedTemplate {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x48
	i--
	if m.ForceDeletePod {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x40
	{
		size, err := m.UpdateStrategy.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.Templates) > 0 {
		keysForTemplates := make([]string, 0, len(m.Templates))
		for k := range m.Templates {
			keysForTemplates = append(keysForTemplates, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForTemplates)
		for iNdEx := len(keysForTemplates) - 1; iNdEx >= 0; iNdEx-- {
			v := m.Templates[string(keysForTemplates[iNdEx])]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintGenerated(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(keysForTemplates[iNdEx])
			copy(dAtA[i:], keysForTemplates[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForTemplates[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Statuses) > 0 {
		keysForStatuses := make([]string, 0, len(m.Statuses))
		for k := range m.Statuses {
			keysForStatuses = append(keysForStatuses, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForStatuses)
		for iNdEx := len(keysForStatuses) - 1; iNdEx >= 0; iNdEx-- {
			v := m.Statuses[string(keysForStatuses[iNdEx])]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintGenerated(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(keysForStatuses[iNdEx])
			copy(dAtA[i:], keysForStatuses[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForStatuses[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.TemplatePool) > 0 {
		keysForTemplatePool := make([]string, 0, len(m.TemplatePool))
		for k := range m.TemplatePool {
			keysForTemplatePool = append(keysForTemplatePool, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForTemplatePool)
		for iNdEx := len(keysForTemplatePool) - 1; iNdEx >= 0; iNdEx-- {
			v := m.TemplatePool[string(keysForTemplatePool[iNdEx])]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i -= len(keysForTemplatePool[iNdEx])
			copy(dAtA[i:], keysForTemplatePool[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForTemplatePool[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.Template.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Selector != nil {
		{
			size, err := m.Selector.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	i = encodeVarintGenerated(dAtA, i, uint64(m.Replicas))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *TAppStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TAppStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TAppStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Statuses) > 0 {
		keysForStatuses := make([]string, 0, len(m.Statuses))
		for k := range m.Statuses {
			keysForStatuses = append(keysForStatuses, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForStatuses)
		for iNdEx := len(keysForStatuses) - 1; iNdEx >= 0; iNdEx-- {
			v := m.Statuses[string(keysForStatuses[iNdEx])]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintGenerated(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(keysForStatuses[iNdEx])
			copy(dAtA[i:], keysForStatuses[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForStatuses[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	i -= len(m.AppStatus)
	copy(dAtA[i:], m.AppStatus)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.AppStatus)))
	i--
	dAtA[i] = 0x2a
	i -= len(m.ScaleLabelSelector)
	copy(dAtA[i:], m.ScaleLabelSelector)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ScaleLabelSelector)))
	i--
	dAtA[i] = 0x22
	i = encodeVarintGenerated(dAtA, i, uint64(m.ReadyReplicas))
	i--
	dAtA[i] = 0x18
	i = encodeVarintGenerated(dAtA, i, uint64(m.Replicas))
	i--
	dAtA[i] = 0x10
	i = encodeVarintGenerated(dAtA, i, uint64(m.ObservedGeneration))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *TAppUpdateStrategy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TAppUpdateStrategy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TAppUpdateStrategy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxUnavailable != nil {
		{
			size, err := m.MaxUnavailable.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	i -= len(m.Template)
	copy(dAtA[i:], m.Template)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Template)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TApp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *TAppList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *TAppSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.Replicas))
	if m.Selector != nil {
		l = m.Selector.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = m.Template.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.TemplatePool) > 0 {
		for k, v := range m.TemplatePool {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + l + sovGenerated(uint64(l))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	if len(m.Statuses) > 0 {
		for k, v := range m.Statuses {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + len(v) + sovGenerated(uint64(len(v)))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	if len(m.Templates) > 0 {
		for k, v := range m.Templates {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + len(v) + sovGenerated(uint64(len(v)))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	l = m.UpdateStrategy.Size()
	n += 1 + l + sovGenerated(uint64(l))
	n += 2
	n += 2
	n += 2
	if len(m.VolumeClaimTemplates) > 0 {
		for _, e := range m.VolumeClaimTemplates {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *TAppStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.ObservedGeneration))
	n += 1 + sovGenerated(uint64(m.Replicas))
	n += 1 + sovGenerated(uint64(m.ReadyReplicas))
	l = len(m.ScaleLabelSelector)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.AppStatus)
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Statuses) > 0 {
		for k, v := range m.Statuses {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + len(v) + sovGenerated(uint64(len(v)))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *TAppUpdateStrategy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Template)
	n += 1 + l + sovGenerated(uint64(l))
	if m.MaxUnavailable != nil {
		l = m.MaxUnavailable.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TApp) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TApp{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "TAppSpec", "TAppSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "TAppStatus", "TAppStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TAppList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]TApp{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "TApp", "TApp", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&TAppList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *TAppSpec) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForVolumeClaimTemplates := "[]PersistentVolumeClaim{"
	for _, f := range this.VolumeClaimTemplates {
		repeatedStringForVolumeClaimTemplates += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForVolumeClaimTemplates += "}"
	keysForTemplatePool := make([]string, 0, len(this.TemplatePool))
	for k := range this.TemplatePool {
		keysForTemplatePool = append(keysForTemplatePool, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForTemplatePool)
	mapStringForTemplatePool := "map[string]v11.PodTemplateSpec{"
	for _, k := range keysForTemplatePool {
		mapStringForTemplatePool += fmt.Sprintf("%v: %v,", k, this.TemplatePool[k])
	}
	mapStringForTemplatePool += "}"
	keysForStatuses := make([]string, 0, len(this.Statuses))
	for k := range this.Statuses {
		keysForStatuses = append(keysForStatuses, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForStatuses)
	mapStringForStatuses := "map[string]InstanceStatus{"
	for _, k := range keysForStatuses {
		mapStringForStatuses += fmt.Sprintf("%v: %v,", k, this.Statuses[k])
	}
	mapStringForStatuses += "}"
	keysForTemplates := make([]string, 0, len(this.Templates))
	for k := range this.Templates {
		keysForTemplates = append(keysForTemplates, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForTemplates)
	mapStringForTemplates := "map[string]string{"
	for _, k := range keysForTemplates {
		mapStringForTemplates += fmt.Sprintf("%v: %v,", k, this.Templates[k])
	}
	mapStringForTemplates += "}"
	s := strings.Join([]string{`&TAppSpec{`,
		`Replicas:` + fmt.Sprintf("%v", this.Replicas) + `,`,
		`Selector:` + strings.Replace(fmt.Sprintf("%v", this.Selector), "LabelSelector", "v1.LabelSelector", 1) + `,`,
		`Template:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Template), "PodTemplateSpec", "v11.PodTemplateSpec", 1), `&`, ``, 1) + `,`,
		`TemplatePool:` + mapStringForTemplatePool + `,`,
		`Statuses:` + mapStringForStatuses + `,`,
		`Templates:` + mapStringForTemplates + `,`,
		`UpdateStrategy:` + strings.Replace(strings.Replace(this.UpdateStrategy.String(), "TAppUpdateStrategy", "TAppUpdateStrategy", 1), `&`, ``, 1) + `,`,
		`ForceDeletePod:` + fmt.Sprintf("%v", this.ForceDeletePod) + `,`,
		`AutoDeleteUnusedTemplate:` + fmt.Sprintf("%v", this.AutoDeleteUnusedTemplate) + `,`,
		`NeverMigrate:` + fmt.Sprintf("%v", this.NeverMigrate) + `,`,
		`VolumeClaimTemplates:` + repeatedStringForVolumeClaimTemplates + `,`,
		`}`,
	}, "")
	return s
}
func (this *TAppStatus) String() string {
	if this == nil {
		return "nil"
	}
	keysForStatuses := make([]string, 0, len(this.Statuses))
	for k := range this.Statuses {
		keysForStatuses = append(keysForStatuses, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForStatuses)
	mapStringForStatuses := "map[string]InstanceStatus{"
	for _, k := range keysForStatuses {
		mapStringForStatuses += fmt.Sprintf("%v: %v,", k, this.Statuses[k])
	}
	mapStringForStatuses += "}"
	s := strings.Join([]string{`&TAppStatus{`,
		`ObservedGeneration:` + fmt.Sprintf("%v", this.ObservedGeneration) + `,`,
		`Replicas:` + fmt.Sprintf("%v", this.Replicas) + `,`,
		`ReadyReplicas:` + fmt.Sprintf("%v", this.ReadyReplicas) + `,`,
		`ScaleLabelSelector:` + fmt.Sprintf("%v", this.ScaleLabelSelector) + `,`,
		`AppStatus:` + fmt.Sprintf("%v", this.AppStatus) + `,`,
		`Statuses:` + mapStringForStatuses + `,`,
		`}`,
	}, "")
	return s
}
func (this *TAppUpdateStrategy) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TAppUpdateStrategy{`,
		`Template:` + fmt.Sprintf("%v", this.Template) + `,`,
		`MaxUnavailable:` + strings.Replace(fmt.Sprintf("%v", this.MaxUnavailable), "IntOrString", "intstr.IntOrString", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TApp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TApp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TApp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TAppList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TAppList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TAppList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, TApp{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TAppSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TAppSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TAppSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicas", wireType)
			}
			m.Replicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Replicas |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Selector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Selector == nil {
				m.Selector = &v1.LabelSelector{}
			}
			if err := m.Selector.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Template", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Template.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TemplatePool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TemplatePool == nil {
				m.TemplatePool = make(map[string]v11.PodTemplateSpec)
			}
			var mapkey string
			mapvalue := &v11.PodTemplateSpec{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthGenerated
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthGenerated
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &v11.PodTemplateSpec{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.TemplatePool[mapkey] = *mapvalue
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Statuses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Statuses == nil {
				m.Statuses = make(map[string]InstanceStatus)
			}
			var mapkey string
			var mapvalue InstanceStatus
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = InstanceStatus(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Statuses[mapkey] = ((InstanceStatus)(mapvalue))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Templates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Templates == nil {
				m.Templates = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Templates[mapkey] = mapvalue
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateStrategy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UpdateStrategy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForceDeletePod", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ForceDeletePod = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoDeleteUnusedTemplate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AutoDeleteUnusedTemplate = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NeverMigrate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NeverMigrate = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumeClaimTemplates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VolumeClaimTemplates = append(m.VolumeClaimTemplates, v11.PersistentVolumeClaim{})
			if err := m.VolumeClaimTemplates[len(m.VolumeClaimTemplates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TAppStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TAppStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TAppStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedGeneration", wireType)
			}
			m.ObservedGeneration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservedGeneration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicas", wireType)
			}
			m.Replicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Replicas |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadyReplicas", wireType)
			}
			m.ReadyReplicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReadyReplicas |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScaleLabelSelector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScaleLabelSelector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppStatus = AppStatus(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Statuses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Statuses == nil {
				m.Statuses = make(map[string]InstanceStatus)
			}
			var mapkey string
			var mapvalue InstanceStatus
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = InstanceStatus(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Statuses[mapkey] = ((InstanceStatus)(mapvalue))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TAppUpdateStrategy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TAppUpdateStrategy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TAppUpdateStrategy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Template", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Template = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxUnavailable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MaxUnavailable == nil {
				m.MaxUnavailable = &intstr.IntOrString{}
			}
			if err := m.MaxUnavailable.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
