---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tapp-controller
  namespace: kube-system

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tapp-controller-role-binding
subjects:
  - kind: ServiceAccount
    name: tapp-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tapp-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: tapp-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: tapp-controller
    spec:
      serviceAccountName: tapp-controller
      containers:
        - name: tapp-controller
          image: tkestack/tapp-controller:v1.1.1
          args:
            - "--v=3"
            - "--register-admission=true"
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8443
            protocol: "TCP"
            name: "https"
          resources:
            requests:
              "cpu": "100m"
              "memory": "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: tapp-controller
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
    targetPort: https
  selector:
    app: tapp-controller
  type: ClusterIP
